// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppLayout: typeof import('./src/views/layouts/appLayout.vue')['default']
    DefaultLayout: typeof import('./src/views/layouts/defaultLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/core/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Undefined: typeof import('./src/views/home/index.vue')['default']
  }
}
